<?php
session_start();
if (!isset($_SESSION['loggedin']) || $_SESSION['user_type'] !== 'Admin') {
    header("location: login.php");
    exit;
}

// Include TCPDF library
require_once('tcpdf_include.php'); // Ensure TCPDF is in your directory or included via Composer

// Database connection
$host = '127.0.0.1';
$db = 'tugaon_db';
$user = 'root';
$pass = '';

$conn = new mysqli($host, $user, $pass, $db);
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// Fetch student details
$id = intval($_GET['id']);
$sql = "SELECT * FROM students WHERE id = $id";
$result = $conn->query($sql);
$student = $result->fetch_assoc();

if (!$student) {
    die("Student not found!");
}

// Assume the profile picture is stored as a path in the database and is in JPG format
$profile_picture_path = $student['profile_picture']; // The path to the student's profile picture

// If the profile picture exists, encode it in base64
if (file_exists($profile_picture_path)) {
    $profile_picture_src = $profile_picture_path; // Direct file path for TCPDF
} else {
    // Use a default image if no profile picture is found
    $profile_picture_src = 'default.jpg'; // Path to default image
}

// Create new PDF document
$pdf = new TCPDF();
$pdf->AddPage();

// Set font
$pdf->SetFont('helvetica', '', 12);

// Add Title
$pdf->SetFont('helvetica', 'B', 16);
$pdf->Cell(0, 10, 'Student Information', 0, 1, 'C');

// Add Profile Picture (scale it appropriately)
$pdf->Image($profile_picture_src, 10, 40, 40, 40, 'JPG');

// Personal Information Section
$pdf->SetFont('helvetica', '', 12);
$pdf->Ln(50); // Line break
$pdf->Cell(0, 10, 'First Name: ' . $student['firstname'], 0, 1);
$pdf->Cell(0, 10, 'Last Name: ' . $student['last_name'], 0, 1);
$pdf->Cell(0, 10, 'Year: ' . $student['student_year'], 0, 1);
$pdf->Cell(0, 10, 'Section: ' . $student['section_of_student'], 0, 1);
$pdf->Cell(0, 10, 'Age: ' . $student['age'], 0, 1);
$pdf->Cell(0, 10, 'Gender: ' . $student['gender'], 0, 1);
$pdf->Cell(0, 10, 'Address: ' . $student['address'], 0, 1);

// Footer text
$pdf->Ln(20);
$pdf->SetFont('helvetica', 'I', 8);
$pdf->Cell(0, 10, 'Generated by TugaOn Student Profiling System', 0, 1, 'C');

// Output PDF
$pdf->Output('student_profile.pdf', 'D');

// Close the database connection
$conn->close();
?>
